java:
  ingressHost: ccd-test-stubs-service-{{ .Values.global.environment }}.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 5555
  image: "hmctspublic.azurecr.io/ccd/test-stubs-service:latest"
  environment:
    WIREMOCK_SERVER_MAPPINGS_PATH: "wiremock"
